distancia=float(input('Diga-me uma distância em metros: '))
print('Isso equivale a ',distancia/1000,' KMs.')
print('Isso equivale a ',distancia/100,' HMs.')
print('Isso equivale a ',distancia/10,' Dams.')
print('Isso equivale a ',distancia*10,' dms.')
print('Isso equivale a ',distancia*100,' cms.')
print('Isso equivale a ',distancia*1000,' mms.')